CREATE TABLE someentity (
  id    INT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ) NOT NULL,
  field VARCHAR(255),
  type VARCHAR(16),
  PRIMARY KEY (id)
);

CREATE TABLE thirdentity (
  id       INT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ) NOT NULL,
  name VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE related (
id       INT GENERATED BY DEFAULT AS IDENTITY (
START WITH 1 ) NOT NULL,
some_id INT   NOT NULL,
third_id INT   NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (some_id) REFERENCES someentity (id),
FOREIGN KEY (third_id) REFERENCES thirdentity (id)
);

CREATE TABLE type (
  id   INT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 )    NOT NULL,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO type (id, name) VALUES (1, 'DERIVED');

CREATE TABLE base (
  id         INT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ) NOT NULL,
  type_id    INT NOT NULL,
  base_field VARCHAR(255),
  PRIMARY KEY (id),
  FOREIGN KEY (type_id) REFERENCES type (id)
);

CREATE TABLE derived (
  base_id       INT NOT NULL,
  derived_field VARCHAR(255),
  PRIMARY KEY (base_id),
  FOREIGN KEY (base_id) REFERENCES base (id)
);
