create table someentity (
  id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
  field varchar(255),
  primary key(id)
);

create table related (
  id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
  other_id int not null,
  primary key(id),
  foreign key(other_id) references someentity(id)
)